### ISSUE TITLE
Client::bulkDelete receives not transformed index name

### ISSUE THREAD

**Issue by egor-dev** [loyaltycorp/search#32]
Hello!
When we call 
```
\LoyaltyCorp\Search\Workers\EntityDeleteWorker::handle([User::class => [<entityId>]]);
```
we get an error `At least one record returned an error during bulk delete`.

The internal elastic response is:
```
Array
(
    [0] => Array
        (
            [delete] => Array
                (
                    [_index] => App\Database\Entities\User
                    [_type] => doc
                    [_id] => e87c8c88-20bc-11ea-a64c-0242c0a86003
                    [status] => 404
                    [error] => Array
                        (
                            [type] => index_not_found_exception
                            [reason] => no such index
                            [resource.type] => index_expression
                            [resource.id] => App\Database\Entities\User
                            [index_uuid] => _na_
                            [index] => App\Database\Entities\User
                        )
                )
        )
)

```
The reason is that `\LoyaltyCorp\Search\Interfaces\Transformers\IndexNameTransformerInterface::transformIndexName` is not involved in the delete process comparing to update.

When we call
```
\LoyaltyCorp\Search\Workers\EntityUpdateWorker::handle([User::class => [<entityId>]]);
```
everything works perfectly.

**Comment by merk** [comment]
Yes, this is something we need to fix, can you please send a PR?

**Comment by egor-dev** [comment]
Surely. I'll do it.

**Comment by egor-dev** [comment]
After discovering I've realized that it's not quite an issue. It's just how the package works. I tried several ways to make it possible, but there will be too many changes. I decided to go a different way in my situation. But if you make it possible to use EntityDeleteWorker as I mentioned - that would be great. @merk, should I close the issue?
